import numpy as np
import pandas as pd

contractMain = [
    { "type":"黑色金属", "name":"铁矿石", "code":"i", "exchange":"DCE" },
    { "type":"黑色金属", "name":"螺纹钢", "code":"rb", "exchange":"SHFE" },
    { "type":"黑色金属", "name":"热卷", "code":"hc", "exchange":"SHFE" },
    { "type":"黑色金属", "name":"不锈钢", "code":"ss", "exchange":"SHFE" },
    { "type":"黑色金属", "name":"硅铁", "code":"SF", "exchange":"CZCE" },
    { "type":"黑色金属", "name":"锰硅", "code":"SM", "exchange":"CZCE" },
    { "type":"有色金属", "name":"沪铜", "code":"cu", "exchange":"SHFE" },
    { "type":"有色金属", "name":"沪铝", "code":"al", "exchange":"SHFE" },
    { "type":"有色金属", "name":"沪锌", "code":"zn", "exchange":"SHFE" },
    { "type":"有色金属", "name":"沪铅", "code":"pb", "exchange":"SHFE" },
    { "type":"有色金属", "name":"沪镍", "code":"ni", "exchange":"SHFE" },
    { "type":"有色金属", "name":"沪锡", "code":"sn", "exchange":"SHFE" },
    { "type":"有色金属", "name":"国际铜", "code":"bc", "exchange":"INE" },
    { "type":"有色金属", "name":"工业硅", "code":"si", "exchange":"GFEX" },
    { "type":"贵金属", "name":"沪金", "code":"au", "exchange":"SHFE" },
    { "type":"贵金属", "name":"沪银", "code":"ag", "exchange":"SHFE" },
    { "type":"油脂油料", "name":"豆一", "code":"a", "exchange":"DCE" },
    { "type":"油脂油料", "name":"豆二", "code":"b", "exchange":"DCE" },
    { "type":"油脂油料", "name":"豆油", "code":"y", "exchange":"DCE" },
    { "type":"油脂油料", "name":"豆粕", "code":"m", "exchange":"DCE" },
    { "type":"油脂油料", "name":"棕榈油", "code":"p", "exchange":"DCE" },
    { "type":"油脂油料", "name":"菜油", "code":"OI", "exchange":"CZCE" },
    { "type":"油脂油料", "name":"菜粕", "code":"RM", "exchange":"CZCE" },
    { "type":"农产品", "name":"玉米", "code":"c", "exchange":"DCE" },
    { "type":"农产品", "name":"淀粉", "code":"cs", "exchange":"DCE" },
    { "type":"农产品", "name":"鸡蛋", "code":"jd", "exchange":"DCE" },
    { "type":"农产品", "name":"棉花", "code":"CF", "exchange":"CZCE" },
    { "type":"农产品", "name":"面纱", "code":"CY", "exchange":"CZCE" },
    { "type":"农产品", "name":"苹果", "code":"AP", "exchange":"CZCE" },
    { "type":"农产品", "name":"红枣", "code":"CJ", "exchange":"CZCE" },
    { "type":"农产品", "name":"花生", "code":"PK", "exchange":"CZCE" },
    { "type":"农产品", "name":"粳米", "code":"rr", "exchange":"DCE" },
    { "type":"农产品", "name":"生猪", "code":"lh", "exchange":"DCE" },
    { "type":"农产品", "name":"白糖", "code":"SR", "exchange":"CZCE" },
    { "type":"能源化工", "name":"原油", "code":"sc", "exchange":"INE" },
    { "type":"能源化工", "name":"LPG", "code":"pg", "exchange":"DCE" },
    { "type":"能源化工", "name":"低硫燃油", "code":"lu", "exchange":"INE" },
    { "type":"能源化工", "name":"沥青", "code":"bu", "exchange":"SHFE" },
    { "type":"能源化工", "name":"甲醇", "code":"MA", "exchange":"CZCE" },
    { "type":"能源化工", "name":"乙二醇", "code":"eg", "exchange":"DCE" },
    { "type":"能源化工", "name":"塑料", "code":"l", "exchange":"DCE" },
    { "type":"能源化工", "name":"PTA", "code":"TA", "exchange":"CZCE" },
    { "type":"能源化工", "name":"聚丙烯", "code":"pp", "exchange":"DCE" },
    { "type":"能源化工", "name":"苯乙烯", "code":"eb", "exchange":"DCE" },
    { "type":"能源化工", "name":"尿素", "code":"UR", "exchange":"CZCE" },
    { "type":"能源化工", "name":"橡胶", "code":"ru", "exchange":"SHFE" },
    { "type":"能源化工", "name":"20号胶", "code":"nr", "exchange":"INE" },
    { "type":"能源化工", "name":"纸浆", "code":"sp", "exchange":"SHFE" },
    { "type":"能源化工", "name":"短纤", "code":"PF", "exchange":"CZCE" },
    { "type":"能源化工", "name":"燃油", "code":"fu", "exchange":"SHFE" },
    { "type":"能源化工", "name":"PVC", "code":"v", "exchange":"DCE" },
    { "type":"能源化工", "name":"纯碱", "code":"SA", "exchange":"CZCE" },
    { "type":"能源化工", "name":"玻璃", "code":"FG", "exchange":"CZCE" },
    { "type":"煤炭板块", "name":"焦煤", "code":"jm", "exchange":"DCE" },
    { "type":"煤炭板块", "name":"焦炭", "code":"j", "exchange":"DCE" },
]

print(contractMain[0]["type"])